name: 'market_pulse'
version: '1.0.0'
config-version: 2
profile: 'market_pulse'
model-paths: ["models"]

models:
  market_pulse:
    staging:
      materialized: view
    marts:
      materialized: table